### ISSUE TITLE
Error en el makefile

### ISSUE THREAD

**Issue by FabsGMartin** [DEIIT/taller-git-y-github#3]
Aunque la plantilla viene incluida en el repo, a la hora de compilarlo sigue buscándola en los archivos del sistema:

`  - Compilando Taller-Git-y-Github.pdf...Could not find data file /usr/share/pandoc/data/templates/eisvogel.tex
make: *** [Makefile:79: charla-taller] Error 97`

**Comment by advy99** [comment]
67c7515ed24fa27b9b3d8e7c2fbcaf3182bff8c3 debería solucionarlo, cierro la Issue y si persiste el error abrela de nuevo
